// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyA-cgfbSKiuagpEjP8w1dmiIO9AVjlhjvI',
    appId: '1:988257088468:web:ef43e429e84c0c3420dc41',
    messagingSenderId: '988257088468',
    projectId: 'foodiy-6a9d9',
    authDomain: 'foodiy-6a9d9.firebaseapp.com',
    storageBucket: 'foodiy-6a9d9.firebasestorage.app',
    measurementId: 'G-1CXBH2C8BF',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDyiQl9KFPBMBZK0nsoGc42-xJv-Fz_fPM',
    appId: '1:988257088468:android:b0e4677771997dc620dc41',
    messagingSenderId: '988257088468',
    projectId: 'foodiy-6a9d9',
    storageBucket: 'foodiy-6a9d9.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBGCUU6U0ADY7y5fwwJ1QDAPl1kB7X09hU',
    appId: '1:988257088468:ios:6b44a5803ff3f26b20dc41',
    messagingSenderId: '988257088468',
    projectId: 'foodiy-6a9d9',
    storageBucket: 'foodiy-6a9d9.firebasestorage.app',
    iosBundleId: 'com.example.foodiy',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBGCUU6U0ADY7y5fwwJ1QDAPl1kB7X09hU',
    appId: '1:988257088468:ios:6b44a5803ff3f26b20dc41',
    messagingSenderId: '988257088468',
    projectId: 'foodiy-6a9d9',
    storageBucket: 'foodiy-6a9d9.firebasestorage.app',
    iosBundleId: 'com.example.foodiy',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyA-cgfbSKiuagpEjP8w1dmiIO9AVjlhjvI',
    appId: '1:988257088468:web:74662efc60faef0c20dc41',
    messagingSenderId: '988257088468',
    projectId: 'foodiy-6a9d9',
    authDomain: 'foodiy-6a9d9.firebaseapp.com',
    storageBucket: 'foodiy-6a9d9.firebasestorage.app',
    measurementId: 'G-QZ84NQMR4X',
  );
}
